version: "3.9"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  web_api:
    image: docker.io/library/garage
    depends_on:
     - postgresql_database
     - redis
     - rabbitmq
    ports:
      - "3002:80"
      - "3003:5001"  # Expose the Swagger port http://localhost:3003/swagger/index.html
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=UserID=postgres;Password=postgres;Server=postgresql_database;Port=5432;Database=SampleDb;Pooling=true;
      - ASPNETCORE_URLS=http://+:5001
      - RabbitMQ__HostName= "rabbitmq"
      - RabbitMQ__Port= "5672"
      - RabbitMQ__UserName= "admin"
      - RabbitMQ__Password= "admin"
      - MINIO_SERVER_ADDRESS=http://minio:9001  # Set the Minio server address
      - MINIO_ACCESS_KEY=yDL20vohVWdTzrZ8OKl6  # Set the Minio access key
      - MINIO_SECRET_KEY=Ce24L9mgnU2y1vVb2Y9xdizaFrmhYXktiRxHynFc  # Set the Minio secret key


  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data 
    environment:
      MINIO_SECRET_KEY: Ce24L9mgnU2y1vVb2Y9xdizaFrmhYXktiRxHynFc
      MINIO_ACCESS_KEY: yDL20vohVWdTzrZ8OKl6
      MINIO_SERVER_ADDRESS: http://minio:9001
    command: server /data --console-address ":9001"
    depends_on:
      - web_api

  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=SampleDb
    ports:
      - "5440:5432"
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./.pgadmin:/root/pgadmin
    ports:
      - "5052:80"
    depends_on:
      - postgresql_database
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data


volumes:
  database-data:
  pgadmin:
  redis-data:
  minio-data:  # Define the minio-data volume here


